//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERConsole.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string _class {
            get {
                return ResourceManager.GetString("_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string actions {
            get {
                return ResourceManager.GetString("actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add class.
        /// </summary>
        internal static string add_class {
            get {
                return ResourceManager.GetString("add_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admit Student.
        /// </summary>
        internal static string admit_student {
            get {
                return ResourceManager.GetString("admit_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all teachers by first name.
        /// </summary>
        internal static string all_teachers_by_name {
            get {
                return ResourceManager.GetString("all_teachers_by_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class&apos;s ID :.
        /// </summary>
        internal static string classs_id {
            get {
                return ResourceManager.GetString("classs_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string execute {
            get {
                return ResourceManager.GetString("execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Students.
        /// </summary>
        internal static string generate_students {
            get {
                return ResourceManager.GetString("generate_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Students, Teachers and Classes.
        /// </summary>
        internal static string generate_students_teachers_and_classes {
            get {
                return ResourceManager.GetString("generate_students_teachers_and_classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate teachers.
        /// </summary>
        internal static string generate_teachers {
            get {
                return ResourceManager.GetString("generate_teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Teachers and Students.
        /// </summary>
        internal static string generate_teachers_and_students {
            get {
                return ResourceManager.GetString("generate_teachers_and_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire teacher.
        /// </summary>
        internal static string hire_teacher {
            get {
                return ResourceManager.GetString("hire_teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lay off student.
        /// </summary>
        internal static string lay_off_student {
            get {
                return ResourceManager.GetString("lay_off_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lay off teacher.
        /// </summary>
        internal static string lay_off_teacher {
            get {
                return ResourceManager.GetString("lay_off_teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That wasn&apos;t int pass again : .
        /// </summary>
        internal static string not_int {
            get {
                return ResourceManager.GetString("not_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass amount of students you want to add: .
        /// </summary>
        internal static string pass_amount_of_students {
            get {
                return ResourceManager.GetString("pass_amount_of_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass amount of teachers you want to add: .
        /// </summary>
        internal static string pass_amount_of_teachers {
            get {
                return ResourceManager.GetString("pass_amount_of_teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass regex.
        /// </summary>
        internal static string pass_regex {
            get {
                return ResourceManager.GetString("pass_regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass the ID of teacher you want to lay off.
        /// </summary>
        internal static string pass_the_id_of_teacher_you_want_to_lay_off {
            get {
                return ResourceManager.GetString("pass_the_id_of_teacher_you_want_to_lay_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass the name of the teacher.
        /// </summary>
        internal static string pass_the_name_of_teacher {
            get {
                return ResourceManager.GetString("pass_the_name_of_teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass the second name of the teacher.
        /// </summary>
        internal static string pass_the_secondname_of_teacher {
            get {
                return ResourceManager.GetString("pass_the_secondname_of_teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove class.
        /// </summary>
        internal static string remove_class {
            get {
                return ResourceManager.GetString("remove_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all teachers matching regex.
        /// </summary>
        internal static string show_all_teachers_matching_regex {
            get {
                return ResourceManager.GetString("show_all_teachers_matching_regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string students {
            get {
                return ResourceManager.GetString("students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student&apos;s ID : .
        /// </summary>
        internal static string students_id {
            get {
                return ResourceManager.GetString("students_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        internal static string teachers {
            get {
                return ResourceManager.GetString("teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher&apos;s ID :.
        /// </summary>
        internal static string teachers_id {
            get {
                return ResourceManager.GetString("teachers_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome in Electronic Register (without grades).
        /// </summary>
        internal static string welcome_message {
            get {
                return ResourceManager.GetString("welcome_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong with your input, try again!.
        /// </summary>
        internal static string wrong_input_message {
            get {
                return ResourceManager.GetString("wrong_input_message", resourceCulture);
            }
        }
    }
}
